portfolio/blog/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from .views import ArticleView, IndexView, TagView#, tags_view

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^(?P<slug>[\w-]+)/$', ArticleView.as_view(), name='article'),
    url(r'^tag/(?P<slug>[\w-]+)/$', TagView.as_view(), name='tag'),
    #url(r'^tag/(?P<tags>[\w-]+(?:\+[\w-]+))/$', tags_view,  name='tags')
)

portfolio/portfolio/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.templatetags.static import static
from django.views.generic.base import RedirectView

from core.views import LandingView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', LandingView.as_view(), name='landing'),
    url(r'^about/$', RedirectView.as_view(url='/#about')),
    url(r'^portfolio/$', RedirectView.as_view(url='/#portfolio')),
    url(r'^contact/$', RedirectView.as_view(url='/#contact')),
    url(r'^resume|cv/$', RedirectView.as_view(url=static('docs/resume_Adam_Beagle.pdf'))),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
)

portfolio/projects/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^countdown-demo/$', TemplateView.as_view(template_name='projects/countdown.html'), name='countdown'),
    url(r'^swscroll-demo/$', TemplateView.as_view(template_name='projects/swscroll.html'), name='swscroll'),
    url(r'^swscroll-info/$', TemplateView.as_view(template_name='projects/swscroll-info.html'), name='swscroll-info'),
)

portfolio/projects/models.py
from django.db import models

from core.models import Image, Link

class Project(models.Model):
    title = models.CharField(max_length=32, primary_key=True)
    slug = models.SlugField()
    image = models.ForeignKey(Image)
    
    type = models.CharField(max_length=32)
    role = models.CharField(max_length=32)
    technology = models.CharField(max_length=64)
    
    description = models.TextField()
    
    source_url = models.OneToOneField(
        Link, 
        related_name="source_project", 
        null=True, 
        blank=True
    )
    
    live_url = models.OneToOneField(
        Link, 
        related_name="liveurl_project", 
        null=True, 
        blank=True
    )
    
    def __str__(self):
        return self.title
        
    class Meta:
        ordering = ['-slug']

portfolio/templates/projects/countdown.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block page_title %}{% block header_title %}Countdown Demo{% endblock header_title %}{% endblock page_title%}

{% block extra_css %}<link href="{% static 'css/countdown.css' %}" rel="stylesheet">{% endblock extra_css %}

{% block content %}
    <pre class="console"><div class="console-output"></div><input class="textbox" id="console-input" name="console-input"></pre>
    <p>This is a live demo of a simple console-based Python game called Countdown. The game itself isn't the interesting part - the goal of this project is to allow a standard interactive text-based Python program, i.e. one using <code>print()</code> and <code>input()</code>, to be usable from a browser without modifying the original code.</p>
    <p>For the vast majority of the game, this simulated terminal is getting its content from a remote Python process. It communicates with a server (a Python <code>http.HTTPServer</code> object) which in turn communicates with the original Python game (launched in a different thread per browser session) via some IO-wrapping magic. At this point, the timer portion is implemented using JavaScript. I hope to discuss the entire process in detail in a blog article soon.</p>
    <p>To play again after quitting, refresh this page.</p>
{% endblock content %}

{% block body_end %}
    <script src="{% static 'js/pyconsole.min.js' %}"></script>
    <script>
        start();
    </script>
{% endblock body_end %}

portfolio/templates/projects/swscroll-info.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block page_title %}{% block header_title %}Star Wars Crawl Demo{% endblock header_title %}{% endblock page_title%}

{% block content %}
    <div class="text-center">
        <div class="project-img-wrapper">
            <img class="img-responsive" src="{% static 'images/projects/swscroll_comparison.png' %}" alt="Demo and film comparison image">
        </div>
    </div>
    <p>The goal of this project was to create a Star Wars opening crawl using only HTML/CSS that is as accurate to the films as possible.</p>
    <p>There are differences in style not only between each film's crawls, but between individual releases of the films. This demo used the 2011 Blu-ray release of Episode IV as a guide.</p>
    <p>CSS3 keyframe animations were used to create both the zoom-out "Star Wars" logo and the crawling text itself. A CSS3 transform rotates the text plane to give the crawl the depth effect from the films. The demo is fully responsive, i.e. it stretches the full width of the browser and the text is the correct size regardless of viewport size. Dynamic text size is accomplished with viewport units. The size of the demo is constrained to the aspect ratio of the film.</p>
    <p><i>A note about music</i><br>The audio of a live performance of the theme found on Youtube is used in place of the true score to avoid legal issues arising from hosting music.</p>
    <div class="text-center">
        <a class="btn btn-default" href="{% url 'projects:swscroll' %}" target="_blank" role="button"><strong>Click to view demo (opens in new tab)</strong></a>
    </div>
{% endblock content %}

portfolio/templates/projects/swscroll.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="{% static 'css/swscroll.css' %}">
  <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
</head>
<body>
  <div id="container">
    <div class="overlay-message">
        <a href="{% url 'projects:swscroll-info' %}">Return to site</a>
    </div>
    <img id="logoimg" src="{% static 'images/projects/swscroll-demo/swlogo.png' %}">
    <div id="scroll-wrapper">
      <div id="scroll">
        <h2 class="episode-number">Episode <span class="episode-number">IV</span></h2>
        <h3 id="episode-title">A New Hope</h3>
        
        <p>
          <span>It is a period of civil war.</span> 
          <span>Rebel spaceships, striking</span> 
          <span>from a hidden base, have won</span>  
          <span>their first victory against</span>
          <span>the evil Galactic Empire.</span>
        </p> 
        
        <p>
          <span>During the battle, Rebel</span>
          <span>spies managed to steal secret</span>
          <span>plans to the Empire's</span>
          <span>ultimate weapon, the DEATH</span>
          <span>STAR, an armored space</span>
          <span>station with enough power to</span>
          <span>destroy an entire planet.</span>
        </p>
        
        <p>
          <span>Pursued by the Empire's</span>
          <span>sinister agents, Princess</span>
          <span>Leia races home aboard her</span>
          <span>starship, custodian of the</span>
          <span>stolen plans that can save</span>
          <span>her people and restore</span>
          <span>freedom to the galaxy....</span>
        </p>
      </div>
    </div>
  </div>

  <iframe class="youtube-embed" width="300" height="300" src="https://www.youtube.com/embed/4rQSJDLM8ZE?autoplay=1&start=3&end=86"></iframe>
  <script>
    $(document).ready(function() {
      function aspectRatioFix() {
        var c = $('#container');
        var b = $('body');
        
        if (window.innerHeight < 0.425*window.innerWidth) {
          b.css('height', 'auto');
          c.css('transform', 'none');
          c.css('top', '0');
        }
        else {
          b.css('height', '100%');
          c.css('transform', 'translateY(-50%)');
          c.css('top', '50%');
        }
      }
      
      aspectRatioFix();
      $(window).resize(aspectRatioFix);
    });
  </script>
</body>
</html>