portfolio/blog/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from .views import ArticleView, IndexView, TagView#, tags_view

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^(?P<slug>[\w-]+)/$', ArticleView.as_view(), name='article'),
    url(r'^tag/(?P<slug>[\w-]+)/$', TagView.as_view(), name='tag'),
    #url(r'^tag/(?P<tags>[\w-]+(?:\+[\w-]+))/$', tags_view,  name='tags')
)

portfolio/portfolio/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.templatetags.static import static
from django.views.generic.base import RedirectView

from core.views import LandingView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', LandingView.as_view(), name='landing'),
    url(r'^about/$', RedirectView.as_view(url='/#about')),
    url(r'^portfolio/$', RedirectView.as_view(url='/#portfolio')),
    url(r'^contact/$', RedirectView.as_view(url='/#contact')),
    url(r'^resume|cv/$', RedirectView.as_view(url=static('docs/resume_Adam_Beagle.pdf'))),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
)

portfolio/blog/models.py
import re

from bs4 import BeautifulSoup
from django.db import models
from django.db.models.signals import m2m_changed, pre_delete
from django.templatetags.static import static
from django.utils.text import slugify
from markdown import markdown
from pygments import highlight
from pygments.lexers import PythonLexer
from pygments.formatters import HtmlFormatter

PYGMENT_CSS_CLASS = 'pygment'

def auto_heading_ids(soup):
    """
    Return soup with automatic slugified ids to any headings ("h#" tags).
    Expects bs4.BeautifulSoup object
    """
    for h in soup.find_all(re.compile('h\d$')):
        s = ''.join(h.strings)
        h['id'] = slugify(s)
        
    return soup

def make_table_of_contents(soup, min_headings=5, label_headings=True):
    """
    Return new BeautifulSoup object containing table of contents for 
    content in 'soup.' Any headings present are included, and are 
    expected to have ids.
    
    If total number of headings is fewer than min_headings, an empty string
    is returned.
    
    Expects bs4.BeautifulSoup object.
    """
    toc = BeautifulSoup()
    
    count_stack = []
    current_ol = None
    previous_li = toc
    previous_heading_name = 'h0'
    i = 0
    
    for i, h in enumerate(soup.find_all(re.compile('h\d$'))):
        if h.name > previous_heading_name:
            current_ol = toc.new_tag('ol')
            count_stack.append(0)
            previous_li.append(current_ol)
        
        else: 
            # Step back to correct ol
            skip = int(previous_heading_name[1]) - int(h.name[1])
            for j in range(skip):
                count_stack.pop()
                current_ol = current_ol.parent.parent
            
        count_stack[-1] += 1
        new_li = soup.new_tag('li')
        a = toc.new_tag('a', href='#' + h['id'])
        a.string = ''.join(h.strings)
        
        if label_headings:
            label_span = soup.new_tag('span')
            label_span['class'] = 'heading-number'
            label_span.string = '.'.join(map(str, count_stack))
            print(h)
            h.insert(0, " ")
            print(h)
            h.insert(0, label_span)
            print(h, '\n')
        
        new_li.append(a)
        current_ol.append(new_li)
        previous_li = new_li
        previous_heading_name = h.name

    return toc if i >= min_headings - 1 else ''

def pygmentize(soup):
    """
    Return 'soup' with code blocks pygmentized.
    
    Expects bs4.BeautifulSoup object
    """
    for code in soup.select('pre > code'):
        
        new_soup = BeautifulSoup(
            highlight(
                code.string, 
                PythonLexer(), 
                HtmlFormatter(cssclass=PYGMENT_CSS_CLASS)
            )
        )
        code.clear()
        for element in new_soup:
            code.append(element)
            
    return soup

def staticify_img_srcs(soup):
    """
    Return `soup` with img tag's src attributes fixed to be static paths,
    as though the src attribute was the argument to a {% static %} template
    tag.
    
    Expects bs4.BeautifulSoup object.
    """
    for img in soup.find_all('img'):
        img['src'] = static(img.get('src'))
        
    return soup



class Tag(models.Model):
    slug = models.SlugField(max_length=32)
    count = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.slug
        
    def save(self, *args, **kwargs):
        #self.count = len(self.article_set.all())
        
        return super().save(*args, **kwargs)
        
    class Meta:
        ordering = ['-count']

class Article(models.Model):
    title = models.CharField(max_length=64)
    subtitle = models.CharField(max_length=128, default='', null=True, blank=True)
    slug = models.SlugField(max_length=32, default='')
    posted = models.DateTimeField()
    tags = models.ManyToManyField(Tag)
    content = models.TextField()
    
    # Auto-created on save
    content_html  = models.TextField()
    toc = models.TextField()
    last_edited = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.full_title

    def save(self, *args, **kwargs):
        soup = BeautifulSoup(markdown(self.content, 
            extensions=['markdown.extensions.footnotes']
        ))
        soup = auto_heading_ids(soup)
        soup = staticify_img_srcs(soup)
        soup = pygmentize(soup)
        toc = make_table_of_contents(soup, label_headings=True)
        
        self.toc = str(toc)
        self.content_html = str(soup)
        
        return super().save(*args, **kwargs)
        
    @property
    def full_title(self):
        if self.subtitle:
            return '{} - {}'.format(self.title, self.subtitle)
        else:
            return self.title
        
    class Meta:
        ordering = ['-posted']

def article_changed(sender, **kwargs):
    """Update Tag.count attributes when articles added, updated, or deleted."""
    article = kwargs['instance']

    # Delete or tag removal
    # Note in case of update with no change for a tag, it "balances out" because
    # it is cleared then added.
    if sender is Article or kwargs['action'] == 'pre_clear':
        for tag in article.tags.all():
            tag.count = max(0, tag.count - 1)
            tag.save()
            
    # Add or update
    elif kwargs['action'] == 'post_add':
        for tag in article.tags.all():
            tag.count += 1
            tag.save()

m2m_changed.connect(article_changed, sender=Article.tags.through)
pre_delete.connect(article_changed, sender=Article)

portfolio/blog/views.py
from os.path import join, isfile

from django.conf import settings
from django.http import Http404
from django.shortcuts import render
from django.templatetags.static import static
from django.views.generic import DetailView, ListView

from .models import Article, Tag

class ArticleView(DetailView):
    template_name = 'blog/article.html'
    model = Article
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        
        # Add banner_path to context, if banner image exists
        # Banner is assumed to be named 'banner.png' and live in a directory
        # inside /images/blog whose name is identical to the article's slug.
        slug = context['article'].slug
        banner_path = static('images/blog/{}/banner.png'.format(slug))
        
        if isfile(join(settings.BASE_DIR, banner_path[1:])):
            context['banner_path'] = str(banner_path)
            self.template_name = 'blog/article_with_banner.html'

        return context
    
class IndexView(ListView):
    model = Article
    paginate_by = 10
    template_name = 'blog/index.html'
    
class TagView(DetailView):
    model = Tag
    template_name = 'blog/tag.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag_string'] = self.kwargs['slug']
        object = context['object']
        
        # If tag requested does not exist, object is None.
        # article_list is empty queryset in that case.
        if object is None:
            context['article_list'] = Article.objects.none()
        else:
            context['article_list'] = object.article_set.all()
        
        return context
        
    def get(self, request, *args, **kwargs):
        """
        In the case that the tag requested does not exist, rather than raise
        Http404, set self.object to None. get_context_data and the template 
        deal with this case appropriately.
        """
        try:
            self.object = self.get_object()
        except Http404:
            self.object = None
            
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

portfolio/templates/blog/article.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% load humanize %}
{% load blog_tags %}

{% block page_title %}{{ article.full_title }}{% endblock page_title %}

{% block header_title %}{{ article.title }}{% endblock header_title %}

{% block header_subtitle %}{% if article.subtitle %}<h2>{{ article.subtitle }}</h2>{% endif %}{% endblock header_subtitle %}

{% block extra_css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'css/pygments.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.min.css' %}">
{% endblock extra_css %}

{% block post_header %}
    <div class=" article-info tags visible-xs visible-sm">Posted {{ article.posted|naturalday }}<br>
    Filed under 
        {% for tag in article.tags.all %}
            <span><a href="{% url 'blog:tag' tag.slug %}">{{ tag.slug }}</a></span>
        {% endfor %}
    </div>
{% endblock post_header %}

{% block article %}
    <div class=" article-info tags hidden-xs hidden-sm">Posted {{ article.posted|naturalday }}<br>
    Filed under 
        {% for tag in article.tags.all %}
            <span><a href="{% url 'blog:tag' tag.slug %}">{{ tag.slug }}</a></span>
        {% endfor %}
    </div>
    {% if article.toc %}
        <h3>Contents</h3>
        <nav role="navigation" class="table-of-contents">
            {{ article.toc|safe }}
        </nav>
    {% endif %}
    <article>
        {{ article.content_html|safe }}
    </article>
{% endblock article %}

{% block body_end %}
    {{ block.super }}
    <script src="{% static 'js/magnificpopup.min.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            /* Add toggle button for lengthy tables of contents */
            toc = $('.table-of-contents');
            if (toc.height() > 300) {
                toc.before('<button type="button" class="btn btn-default showhide-btn">&gt;&gt; Show &gt;&gt;&gt;</button>');
                showhideBtn = $('.showhide-btn');
                showhideBtn.click(function() {
                    toc.slideToggle();
                    
                    if(showhideBtn.text() == ">> Show >>>")
                        showhideBtn.text('<<< Hide <<');
                    else
                        showhideBtn.text('>> Show >>>');
                });
            }
            else {
                toc.show();
            }
            
            /* Add <hr> between major section headings  */
            majorHeadings = $('nav.table-of-contents+article h3:not(:first-of-type)');
            majorHeadings.before('<hr>');
            majorHeadings.css('margin-top', '0');
            
            /* Enable magnificPopup */
            $('.popup-gallery').each( function() {
                $(this).magnificPopup({
                    delegate: 'div a',
                    type: 'image',
                    tLoading: 'Loading image #%curr%...',
                    mainClass: 'mfp-img-mobile',
                    gallery: {
                        enabled: true,
                        navigateByImgClick: true,
                        preload: [0,1] // Will preload 0 - before current, and 1 after the current image
                    },
                    image: {
                        tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
                        titleSrc: function(item) {
                            return item.el.attr('title');
                        }
                    }
                });
            });
        });
    </script>
{% endblock body_end %}

portfolio/templates/blog/article_with_banner.html
{% extends 'blog/article.html' %}

{% block content_col_extraclass %}{{ block.super }} disable-border{% endblock content_col_extraclass %}

portfolio/templates/blog/base.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra_css %}
    <link href="{% static 'css/blog.min.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block navbar-fixed %}{% endblock navbar-fixed %}
    
{% block content %}   
    {% block article %}{% endblock article %}
    <div class="share-btn"></div>
{% endblock content %}

{% block body_end %}
    {{ block.super }}
    {% block share_button %}
        <script src="{% static 'js/share.min.js' %}" type="text/javascript"></script>
        <script type="text/javascript">
            var share = new Share('.share-btn');
        </script>
    {% endblock share_button %}
{% endblock body_end %}

portfolio/templates/blog/base_index.html
{% extends 'blog/base.html' %}
{% load humanize %}

{% block content_col_extraclass %}disable-border{% endblock %}

{% block article%}
    {% if article_list %}
        <table class="table blog-index">
            <tr>
                <th>Title</th>
                <th class="hidden-xxs">Date</th>
                <th class="hidden-xs">Tags</th>
            </tr>
            {% for article in article_list %}
                <tr>
                    <td>
                        <a href="{% url 'blog:article' article.slug %}">{{ article.full_title }}</a>
                    </td>
                    
                    <td class="hidden-xxs">
                        <span class="hidden-xs">
                            {{ article.posted|naturalday }}
                        </span>
                        <span class="visible-xs">
                            {{ article.posted|date:"SHORT_DATE_FORMAT" }}
                        </span>
                    </td>
                    
                    <td class="tags hidden-xs">
                        {% for tag in article.tags.all %}
                            <span><a href="{% url 'blog:tag' tag.slug %}">{{ tag.slug }}</a></span>
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p class="text-center top-spacer">{% block empty_article_set %}No articles yet.{% endblock empty_article_set %}</p>
    {% endif %}
    
    {% if is_paginated %}
        <ul class="pager">
            {% if page_obj.has_previous %}
                <li><a href="/blog?page={{ page_obj.previous_page_number }}">previous</a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li><a href="/blog?page={{ page_obj.next_page_number }}">next</a></li>
            {% endif %}
        </ul>
        <p class="text-center current-page">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</p>
    {% endif %}
    
{% endblock article %}

portfolio/templates/blog/index.html
{% extends 'blog/base_index.html' %}

{% block page_title %}{% block header_title %}Blog{% endblock header_title %}{% endblock page_title %}

{% block index-li %}
    {{ block.super }}
    class="active"
{% endblock index-li %}

portfolio/templates/blog/tag.html
{% extends 'blog/base_index.html' %}
{% load blog_tags %}

{% block page_title %}Tag - {{ tag_string }}{% endblock page_title %}

{% block header_title %}Blog{% endblock header_title %}

{% block header_subtitle %}<h2>tag: {{ tag_string }}</h2>{% endblock header_subtitle %}

{% block post_nav %}
    {% breadcrumb tag_string 'tag' %}
{% endblock post_nav %}

{% block empty_article_set %}Tag does not exist{% endblock empty_article_set %}

{% block share_button%}{% endblock %}